dEdX_calibration -i ../input_run5387.txt -c ../fcl_files/dEdx_calib_Birk_1.5.fcl -o output_1.5.root
dEdX_calibration -i ../input_run5387.txt -c ../fcl_files/dEdx_calib_Birk_1.6.fcl -o output_1.6.root
dEdX_calibration -i ../input_run5387.txt -c ../fcl_files/dEdx_calib_Birk_1.7.fcl -o output_1.7.root
dEdX_calibration -i ../input_run5387.txt -c ../fcl_files/dEdx_calib_Birk_1.8.fcl -o output_1.8.root
dEdX_calibration -i ../input_run5387.txt -c ../fcl_files/dEdx_calib_Birk_1.9.fcl -o output_1.9.root
dEdX_calibration -i ../input_run5387.txt -c ../fcl_files/dEdx_calib_Birk_2.0.fcl -o output_2.0.root
dEdX_calibration -i ../input_run5387.txt -c ../fcl_files/dEdx_calib_Birk_2.1.fcl -o output_2.1.root
dEdX_calibration -i ../input_run5387.txt -c ../fcl_files/dEdx_calib_Birk_2.2.fcl -o output_2.2.root
dEdX_calibration -i ../input_run5387.txt -c ../fcl_files/dEdx_calib_Birk_2.3.fcl -o output_2.3.root
dEdX_calibration -i ../input_run5387.txt -c ../fcl_files/dEdx_calib_Birk_2.4.fcl -o output_2.4.root
dEdX_calibration -i ../input_run5387.txt -c ../fcl_files/dEdx_calib_Birk_2.5.fcl -o output_2.5.root
